@startuml
class ItemListManager{
- application : ToDoListApp
+ sortTasks()
+ delete()
+ add()
+ setTableEditable()
+ displayUncompletedTasks()
+ displayCompletedTasks()
+ save()
+ new()
+ close()
+ open()
}

class ItemListController {
    - todolistTableManager: TodolistTableManager
    - itemsDataList: ObservableList<Item>
    - itemsDataIncomplete: ObservableList<Item>
    - itemsDataComplete: ObservableList<Item>
    - itemsTableView: TableView<Item>
    - toDoColumn :TableColumn
    - items: TableColumn
    - descriptionColumn:T ableColumn
    - dueDateColumn: TableColumn
    - itemName: TextField
    - description: TextField
    - addItem: Button
    - dueDate: TextField

     + initialize()
     + addItemButtonClicked()
     + saveItemMenuClicked()
     + deleteItemClicked()
     + showCompleteMenuClicked()
     + showInCompleteMenuClicked()
     + newMenuClicked()
     + openMenuClicked()
     + closeMenuClicked()
     + dueDateSelectClicked()
     + mouseClicked()




}

class Item{
    -  itemName : SimpleStringProperty
    -  description : SimpleStringProperty
    -  datePattern :String
    -  dueDate: SimpleDateFormat
    -  status : SimpleStringProperty
    + TaskItem()
    + getItemName()
    + setItemName(String itemName)
    + public String getDescription()
    + setDescription(String description)
    + getDueDate()
    + getStatus()
    + setStatus()

}

class ItemListApp{
    main()
    start()
}

javafx.Application <|-- ItemListApp
ItemListApp-ItemListController
ItemListController - Item
ItemListController *-- ItemListManager

@enduml